{
    "openapi": "3.1.1",
    "info": {
        "title": "API para o Departamento de Polícia",
        "summary": "API para gerenciar casos e agentes policiais",
        "description": "Essa API permite o gerenciamento de casos policiais e agentes, incluindo operações CRUD para ambos.",
        "termsOfService": "http://localhost:3000/terms/",
        "contact": {
            "name": "Gabriel",
            "email": "gabriellvbs14@gmail.com"
        },
        "license": {
            "name": "MIT"
        },
        "version": "1.0.0"
    },
    "servers": [
        {
            "url": "http://localhost:3000",
            "description": "Ambiente de desenvolvimento"
        }
    ],
    "paths": {
        "/agentes":{
            "get": {
                "summary": "Retorna uma lista de agentes",
                "description": "Essa rota retorna uma lista de todos os agentes cadastrados.",
                "parameters": [
                    {
                        "name": "id",
                        "in": "query",
                        "description": "Id para filtrar agentes",
                        "required": false,
                        "schema": {
                            "type": "string"
                        },
                        "style": "form",
                        "explode": true
                    },
                    {
                        "name": "nome",
                        "in": "query",
                        "description": "Nome para filtrar agentes",
                        "required": false,
                        "schema": {
                            "type": "string"
                        },
                        "style": "form",
                        "explode": true
                    },
                    {
                        "name": "dataDeIncorporacao",
                        "in": "query",
                        "description": "dataDeIncorporacao para filtrar agentes",
                        "required": false,
                        "schema": {
                            "type": "string"
                        },
                        "style": "form",
                        "explode": true
                    },
                    {
                        "name": "cargo",
                        "in": "query",
                        "description": "Cargo para filtrar agentes",
                        "required": false,
                        "schema": {
                            "type": "string"
                        },
                        "style": "form",
                        "explode": true
                    },
                    {
                        "name": "sort",
                        "in": "query",
                        "description": "Ordenar por um campo específico",
                        "required": false,
                        "schema": {
                            "type": "string"
                        },
                        "style": "form",
                        "explode": true
                    }
                ],
                "tags": ["Gets"],
                "responses": {
                    "200": {
                        "description": "Retorna todos os agentes cadastrados",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "example": [
                                        {
                                            "id": "4dcd8f2a-1a2f-4786-af0a-d7baee70f270",
                                            "nome": "Rommel Carneiro",
                                            "dataDeIncorporacao": "1992-10-04",
                                            "cargo": "delegado"
                                        },
                                        {
                                            "id": "c93dea02-c8dd-4fa6-bba5-2bc2661dbff8",
                                            "nome": "Ana Silva",
                                            "dataDeIncorporacao": "2000-05-12",
                                            "cargo": "investigador"
                                        }
                                    ]
                                }
                            }
                        }
                    }
                }
            },
            "post": {
                "summary": "Cria o registro de um novo agente",
                "description": "Essa rota cria o registro de um novo agente e retorna o agente criado.",
                "tags": ["Posts"],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/AgentePostBody"
                            }
                        }
                    },
                    "required": ["nome", "dataDeIncorporacao", "cargo"]
                },
                "responses": {
                    "201": {
                        "description": "Retorna o agente criado com sucesso",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/AgentePost"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Erro ao criar o agente, devido a dados inválidos",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/AgentePostErroParametros"
                                }
                            }
                        }
                    }
                }
            }
            
        },
        "/agentes/{id}":{
            "get": {
                "summary": "Retorna um agentes",
                "description": "Essa rota retorna um agente cadastrado com determinado id.",
                "parameters": [
                    {
                    "name": "id",
                    "in": "path",
                    "description": "Id do agente para ser retornado",
                    "required": true,
                    "schema": {
                        "type": "string"
                    }
                    }
                ],
                "tags": ["Gets"],
                "responses": {
                    "200": {
                        "description": "Retorna o agente cadastrado com id especificado",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "example": {
                                        "id": "4dcd8f2a-1a2f-4786-af0a-d7baee70f270",
                                        "nome": "Rommel Carneiro",
                                        "dataDeIncorporacao": "1992-10-04",
                                        "cargo": "delegado"
                                    }
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Erro ao encontrar o agente inexistente",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/AgenteInexistenteErro"
                                }
                            }
                        }
                    }
                }
            },
            "put": {
                "summary": "Atualiza completamente o registro de um agente",
                "description": "Essa rota atualiza completamente o registro de um agente e retorna o agente atualizado.",
                "parameters": [
                    {
                    "name": "id",
                    "in": "path",
                    "description": "Id do agente para ser atualizado",
                    "required": true,
                    "schema": {
                        "type": "string"
                    }
                    }
                ],
                "tags": ["Puts"],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/AgentePostBody"
                            }
                        }
                    },
                    "required": ["nome", "dataDeIncorporacao", "cargo"]
                },
                "responses": {
                    "200": {
                        "description": "Retorna o agente criado com sucesso",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/AgentePutSucesso"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Erro ao atualizar o agente, devido a dados inválidos",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/AgentePostErroParametros"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Erro ao atualizar o agente inexistente",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/AgenteInexistenteErro"
                                }
                            }
                        }
                    }
                }
            },
            "patch": {
                "summary": "Atualiza parcialmente o registro de um agente",
                "description": "Essa rota atualiza parcialmente o registro de um agente e retorna o agente atualizado.",
                "parameters": [
                    {
                    "name": "id",
                    "in": "path",
                    "description": "Id do agente para ser atualizado",
                    "required": true,
                    "schema": {
                        "type": "string"
                    }
                    }
                ],
                "tags": ["Patches"],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/AgentePostBody"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Retorna o agente criado com sucesso",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/AgentePatchSucesso"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Erro ao atualizar parcialmente o agente, devido a dados inválidos",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/AgentePostErroParametros"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Erro ao atualizar parcialmente o agente inexistente",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/AgenteInexistenteErro"
                                }
                            }
                        }
                    }
                }
            },
            "delete": {
                "summary": "Deleta o registro de um agentes",
                "description": "Essa rota deleta o registro de um agente",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Id do agente para ser excluído",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "tags": ["Deletes"],
                "responses": {
                    "200": {
                        "description": "Retorna o agente criado com sucesso",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/AgentePatchSucesso"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Erro ao deletar o agente inexistente",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/AgenteInexistenteErro"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/casos": {
            "get": {
                "summary": "Retorna uma lista de casos",
                "description": "Essa rota retorna uma lista de todos os agentes cadastrados.",
                "parameters": [
                    {
                        "name": "id",
                        "in": "query",
                        "description": "Id para filtrar casos",
                        "required": false,
                        "schema": {
                            "type": "string"
                        },
                        "style": "form",
                        "explode": true
                    },
                    {
                        "name": "titulo",
                        "in": "query",
                        "description": "Título para filtrar casos",
                        "required": false,
                        "schema": {
                            "type": "string"
                        },
                        "style": "form",
                        "explode": true
                    },
                    {
                        "name": "descricao",
                        "in": "query",
                        "description": "Descrição para filtrar casos",
                        "required": false,
                        "schema": {
                            "type": "string"
                        },
                        "style": "form",
                        "explode": true
                    },
                    {
                        "name": "status",
                        "in": "query",
                        "description": "Status para filtrar casos",
                        "required": false,
                        "schema": {
                            "type": "string"
                        },
                        "style": "form",
                        "explode": true
                    },
                    {
                        "name": "agente_id",
                        "in": "query",
                        "description": "Agente_id para filtrar agentes responsáveis do caso",
                        "required": false,
                        "schema": {
                            "type": "string"
                        },
                        "style": "form",
                        "explode": true
                    },
                    {
                        "name": "sort",
                        "in": "query",
                        "description": "Ordenar por um campo específico",
                        "required": false,
                        "schema": {
                            "type": "string"
                        },
                        "style": "form",
                        "explode": true
                    }
                ],
                "tags": ["Gets"],
                "responses": {
                    "200": {
                        "description": "Retorna todos os casos cadastrados",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "example": [
                                        {
                                            "id": "58260de7-7be3-4d02-94e4-4c8f51b5fe59",
                                            "titulo": "homicidio",
                                            "descricao": "Disparos foram reportados às 22:33 do dia 10/07/2007 na região do bairro União, resultando na morte da vítima, um homem de 45 anos.",
                                            "status": "aberto",
                                            "agente_id": "553f2b26-331e-4302-97d8-fb5b9a95cba8"
                                        },
                                        {
                                            "id": "43b1333d-c8b3-41d8-a61c-d51891baa048",
                                            "titulo": "roubo",
                                            "descricao": "Assalto a mão armada em uma loja de conveniência no centro às 19:15 do dia 12/08/2010.",
                                            "status": "solucionado",
                                            "agente_id": "c93dea02-c8dd-4fa6-bba5-2bc2661dbff8"
                                        }
                                    ]
                                }
                            }
                        }
                    }
                }
            },
            "post": {
                "summary": "Cria o registro de um novo caso",
                "description": "Essa rota cria o registro de um novo caso e retorna o caso criado.",
                "tags": ["Posts"],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/CasoPostBody"
                            }
                        }
                    },
                    "required": ["titulo", "descricao", "status", "agente_id"]
                },
                "responses": {
                    "201": {
                        "description": "Retorna o caso criado com sucesso",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/CasoPost"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Erro ao criar o caso, devido a dados inválidos",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/CasoPostErroParametros"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/casos/{id}":{
            "get": {
                "summary": "Retorna um caso",
                "description": "Essa rota retorna um caso cadastrado com determinado id.",
                "parameters": [
                    {
                    "name": "id",
                    "in": "path",
                    "description": "Id do caso para ser retornado",
                    "required": true,
                    "schema": {
                        "type": "string"
                    }
                    }
                ],
                "tags": ["Gets"],
                "responses": {
                    "200": {
                        "description": "Retorna o caso cadastrado com id especificado",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "example": {
                                        "id": "c93dea02-c8dd-4fa6-bba5-2bc2661dbff8",
                                        "nome": "Ana Silva",
                                        "dataDeIncorporacao": "2000-05-12",
                                        "cargo": "investigador"
                                    }
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Erro ao buscar o caso inexistente",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/CasoInexistenteErro"
                                }
                            }
                        }
                    }
                }
            },
            "put": {
                "summary": "Atualiza completamente o registro de um caso",
                "description": "Essa rota atualiza completamente o registro de um caso e retorna o caso atualizado.",
                "parameters": [
                    {
                    "name": "id",
                    "in": "path",
                    "description": "Id do caso para ser atualizado",
                    "required": true,
                    "schema": {
                        "type": "string"
                    }
                    }
                ],
                "tags": ["Puts"],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/CasoPostBody"
                            }
                        }
                    },
                    "required": ["titulo", "descricao", "status", "agente_id"]
                },
                "responses": {
                    "200": {
                        "description": "Retorna o caso criado com sucesso",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/CasoPutSucesso"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Erro ao atualizar o caso, devido a dados inválidos",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/CasoPostErroParametros"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Erro ao atualizar o caso inexistente",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/CasoInexistenteErro"
                                }
                            }
                        }
                    }
                }
            },
            "patch": {
                "summary": "Atualiza parcialmente o registro de um caso",
                "description": "Essa rota atualiza parcialmente o registro de um caso e retorna o caso atualizado.",
                "parameters": [
                    {
                    "name": "id",
                    "in": "path",
                    "description": "Id do caso para ser atualizado",
                    "required": true,
                    "schema": {
                        "type": "string"
                    }
                    }
                ],
                "tags": ["Patches"],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/CasoPostBody"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Retorna o caso criado com sucesso",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/CasoPatchSucesso"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Erro ao criar o caso, devido a dados inválidos",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/CasoPostErroParametros"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Erro ao atualizar o caso inexistente",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/CasoInexistenteErro"
                                }
                            }
                        }
                    }
                }
            },
            "delete": {
                "summary": "Deleta o registro de um caso",
                "description": "Essa rota deleta o registro de um caso",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Id do caso para ser excluído",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "tags": ["Deletes"],
                "responses": {
                    "200": {
                        "description": "Retorna o caso criado com sucesso",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/CasoPatchSucesso"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Erro ao deletar o caso inexistente",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/CasoInexistenteErro"
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "components":{
        "schemas":{
            "AgentePost": {
                "type": "object",
                "required": ["id", "nome", "dataDeIncorporacao", "cargo"],
                "properties":{
                    "id":{
                        "type": "string",
                        "format": "uuid"
                    },
                    "nome": {
                        "type": "string"
                    },
                    "dataDeIncorporacao": {
                        "type": "string",
                        "format": "DD-MM-YYYY"
                    },
                    "cargo": {
                        "type": "string"
                    }
                }
            },
            "AgentePostBody": {
                "type": "object",
                "required": ["nome", "dataDeIncorporacao", "cargo"],
                "properties":{
                    "nome": {
                        "type": "string"
                    },
                    "dataDeIncorporacao": {
                        "type": "string"
                    },
                    "cargo": {
                        "type": "string"
                    }
                }
            },
            "AgentePostErroParametros": {
                "type": "object",
                "properties": {
                    "status": {
                        "type": "integer",
                        "example": 400
                    },
                    "message": {
                        "type": "string",
                        "example": "Parâmetros inválidos"
                    },
                    "errors": {
                        "type": "array",
                        "example": [
                            {"nome": "A requisição deve possuir o campo 'nome'"},
                            {"dataDeIncorporacao": "A requisição deve possuir o campo 'dataDeIncorporacao'"},
                            {"dataDeIncorporacao": "Campo dataDeIncorporacao deve seguir a formatação 'YYYY-MM-DD' "},
                            {"dataDeIncorporacao": "Campo dataDeIncorporacao não pode ser uma data futura "},
                            {"cargo": "A requisição deve possuir o campo 'cargo'"}
                        ]
                    }

                }
            },
            "AgenteInexistenteErro": {
                "type": "object",
                "properties":{
                    "status": {
                        "type": "integer",
                        "example": 404
                    },
                    "message": {
                        "type": "string",
                        "example": "Agente não encontrado"
                    },
                    "errors": {
                        "type": "array",
                        "example": [
                            {"id": "Não existe agente com esse id"}
                        ]
                    }
                }
            },
            "AgentePutSucesso": {
                "type": "object",
                "required": ["status", "message", "id", "nome", "dataDeIncorporacao", "cargo"],
                "properties":{
                    "status": {
                        "type": "integer",
                        "example": 200
                    },
                    "message": {
                        "type": "string",
                        "example": "Atualização realizada com sucesso"
                    },
                    "id":{
                        "type": "string",
                        "format": "uuid"
                    },
                    "nome": {
                        "type": "string"
                    },
                    "dataDeIncorporacao": {
                        "type": "string",
                        "format": "DD-MM-YYYY"
                    },
                    "cargo": {
                        "type": "string"
                    }
                }
            },
            "AgentePatchSucesso": {
                "type": "object",
                "required": ["status", "message", "id", "nome", "dataDeIncorporacao", "cargo"],
                "properties":{
                    "status": {
                        "type": "integer",
                        "example": 200
                    },
                    "message": {
                        "type": "string",
                        "example": "Atualização parcial realizada com sucesso"
                    },
                    "id":{
                        "type": "string",
                        "format": "uuid"
                    },
                    "nome": {
                        "type": "string"
                    },
                    "dataDeIncorporacao": {
                        "type": "string",
                        "format": "DD-MM-YYYY"
                    },
                    "cargo": {
                        "type": "string"
                    }
                }
            },
            "CasoPost": {
                "type": "object",
                "required": ["id", "titulo", "descricao", "status", "agente_id"],
                "properties":{
                    "id":{
                        "type": "string",
                        "format": "uuid"
                    },
                    "titulo": {
                        "type": "string"
                    },
                    "descricao": {
                        "type": "string"
                    },
                    "status": {
                        "type": "string"
                    },
                    "agente_id":{
                        "type": "string",
                        "format": "uuid"
                    }
                }
            },
            "CasoPostBody": {
                "type": "object",
                "required": ["titulo", "descricao", "status", "agente_id"],
                "properties":{
                    "titulo": {
                        "type": "string"
                    },
                    "descricao": {
                        "type": "string"
                    },
                    "status": {
                        "type": "string"
                    },
                    "agente_id":{
                        "type": "string",
                        "format": "uuid"
                    }
                }
            },
            "CasoPostErroParametros": {
                "type": "object",
                "properties": {
                    "status": {
                        "type": "integer",
                        "example": 400
                    },
                    "message": {
                        "type": "string",
                        "example": "Parâmetros inválidos"
                    },
                    "errors": {
                        "type": "array",
                        "example": [
                            {"titulo": "A requisição deve possuir o campo 'titulo'"},
                            {"descricao": "A requisição deve possuir o campo 'descricao'"},
                            {"status": "A requisição deve possuir o campo 'status'"},
                            {"status": "O campo 'status' pode ser somente 'aberto' ou 'solucionado'"}
                        ]
                    }

                }
            },
            "CasoInexistenteErro": {
                "type": "object",
                "properties":{
                    "status": {
                        "type": "integer",
                        "example": 404
                    },
                    "message": {
                        "type": "string",
                        "example": "Caso não encontrado"
                    },
                    "errors": {
                        "type": "array",
                        "example": [
                            {"id": "Não existe caso com esse id"}
                        ]
                    }
                }
            },
            "CasoAgenteInexistenteErro": {
                "type": "object",
                "properties":{
                    "status": {
                        "type": "integer",
                        "example": 404
                    },
                    "message": {
                        "type": "string",
                        "example": "Agente não encontrado"
                    },
                    "errors": {
                        "type": "array",
                        "example": [
                            {"agente_id": "Não existe agente com esse id"}
                        ]
                    }
                }
            },
            "CasoPutSucesso": {
                "type": "object",
                "required": ["status", "message", "id", "titulo", "descricao", "agente_id"],
                "properties":{
                    "status": {
                        "type": "string"
                    },
                    "message": {
                        "type": "string",
                        "example": "Atualização realizada com sucesso"
                    },
                    "id":{
                        "type": "string",
                        "format": "uuid"
                    },
                    "titulo": {
                        "type": "string"
                    },
                    "descricao": {
                        "type": "string"
                    },
                    "agente_id":{
                        "type": "string",
                        "format": "uuid"
                    }
                }
            },
            "CasoPatchSucesso": {
                "type": "object",
                "required": ["status", "message", "id", "titulo", "descricao", "agente_id"],
                "properties":{
                    "status": {
                        "type": "string"
                    },
                    "message": {
                        "type": "string",
                        "example": "Atualização parcial realizada com sucesso"
                    },
                    "id":{
                        "type": "string",
                        "format": "uuid"
                    },
                    "titulo": {
                        "type": "string"
                    },
                    "descricao": {
                        "type": "string"
                    },
                    "agente_id":{
                        "type": "string",
                        "format": "uuid"
                    }
                }
            }
        }
    }
}